# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update github-actions"
    groups:
      github-actions-version-updates:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directories:
      - "/" # Searches for uv.lock in Root
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update uv"
    groups:
      uv-version-updates:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/" # Searches for Dockerfile in Root
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update docker images"
    groups:
      docker-version-updates:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories:
      - "/" # Searches for pyproject.toml in Root
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps): update pip"
    groups:
      python-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
