repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-illegal-windows-names
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-xml
        # Full check against all YAML files excluding mkdocs.yml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: destroyed-symlinks
    -   id: detect-private-key
    -   id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
    -   id: forbid-submodules
    -   id: pretty-format-json
        exclude: ^docusaurus\/package-lock.json$
        args: [ --autofix ]
    -   id: trailing-whitespace

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
