name: pip-audit

on:
  push:
    branches: ["main"]
    paths: ["uv.lock"]
  pull_request:
    branches: ["main"]
    paths: ["uv.lock"]

permissions: {}

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2

      - name: Set up Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --frozen --all-extras

      - name: Run pip-audit
        run: uv tool run pip-audit --require-hashes --no-deps -r <(uv export --frozen --no-dev --no-emit-project)
